# Generated by Django 3.1.3 on 2020-12-03 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
    ]
