# Generated by Django 3.1.3 on 2020-11-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201126_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='product_images')),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
