# Generated by Django 3.1.3 on 2020-12-05 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_name'),
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershoppingcart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product'),
        ),
    ]
