# Generated by Django 3.1.3 on 2020-12-06 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_authentication', '0003_auto_20201205_2232'),
        ('basket', '0002_usershoppingcart_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='app_authentication.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductLineItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basket.basket')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.product')),
            ],
        ),
        migrations.DeleteModel(
            name='UserShoppingCart',
        ),
    ]
