# Generated by Django 3.1.3 on 2020-12-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_auto_20201206_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productlineitems',
            name='product_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
