# Generated by Django 3.1.3 on 2020-12-06 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_name'),
        ('basket', '0004_auto_20201206_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlineitems',
            name='id',
        ),
        migrations.RemoveField(
            model_name='productlineitems',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='productlineitems',
            name='product_quantity',
        ),
        migrations.AddField(
            model_name='productlineitems',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.product'),
            preserve_default=False,
        ),
    ]
