# Generated by Django 3.1.3 on 2020-12-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0010_auto_20201210_2014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBasket',
        ),
    ]
